task:
  name: test [ARM]
  arm_container:
    image: rust:1.63.0
    cpu: 8
    memory: 8G
  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  build_script:
    - apt-get update -qqy
    - apt-get install -qqy clang
    - rustup component add clippy rustfmt
    - cargo check --all --locked
    - cargo build --all --locked
  test_script:
    - cargo test --all --locked
    - cargo clippy -- -D warnings
    - cargo fmt --all -- --check
  before_cache_script: rm -rf $CARGO_HOME/registry/index
